{
 "title": "Ikev2 monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"strongswan\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "connection timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (instance, user) (\n  strongswan_user_connected{job=\"strongswan\", instance=~\"$instance\"}\n)\n",
     "legendFormat": "{{instance}} / {{user}}"
    }
   ]
  },
  {
   "title": "unique users connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "count(count by (user) (strongswan_user_connected{job=\"strongswan\", instance=~\"$instance\"} == 1))\n",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "conn duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  20,\n  sum_over_time(\n    (max by (user) (strongswan_user_connected{job=\"strongswan\", instance=~\"$instance\"} == 1))[$__range:1m]\n  )\n)\n",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "connected now",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "strongswan_user_connected{job=\"strongswan\", instance=~\"$instance\"} == 1\n",
     "legendFormat": "{{user}} @ {{remote_addr}} ({{conn}})"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total VPN Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(strongswan_child_bytes_in_total{job=\"strongswan\", instance=~\"$instance\"}[$__range]) +\n  increase(strongswan_child_bytes_out_total{job=\"strongswan\", instance=~\"$instance\"}[$__range])\n) / 1048576\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Users by Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (user) (\n    increase(strongswan_child_bytes_in_total{job=\"strongswan\", instance=~\"$instance\"}[$__range]) +\n    increase(strongswan_child_bytes_out_total{job=\"strongswan\", instance=~\"$instance\"}[$__range])\n  ) / 1048576\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total throughput (in+out) Mbit/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(\n  rate(strongswan_child_bytes_in_total{job=\"strongswan\", instance=~\"$instance\"}[$__rate_interval])\n+ rate(strongswan_child_bytes_out_total{job=\"strongswan\", instance=~\"$instance\"}[$__rate_interval])\n) * 8\n",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Throughput split (in/out), Mbit/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(strongswan_child_bytes_in_total{job=\"strongswan\", instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(strongswan_child_bytes_out_total{job=\"strongswan\", instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Top users by throughput (in+out), Mbit/s",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (user) (\n    rate(strongswan_child_bytes_in_total{job=\"strongswan\", instance=~\"$instance\"}[$__rate_interval])\n  + rate(strongswan_child_bytes_out_total{job=\"strongswan\", instance=~\"$instance\"}[$__rate_interval])\n  )\n) * 8\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}